"use client";

import * as React from "react";
import { motion, useInView, animate, useMotionValue } from "framer-motion";
import { GoldStar } from "@/components/aurienta-logo";
import { useLanguage } from "@/lib/i18n/language-context";

function CountUp({
  to,
  suffix = "",
  prefix = "",
  decimals = 0,
}: {
  to: number;
  suffix?: string;
  prefix?: string;
  decimals?: number;
}) {
  const ref = React.useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: "-40px" });
  const mv = useMotionValue(0);
  const [display, setDisplay] = React.useState("0");

  React.useEffect(() => {
    if (!inView) return;
    const controls = animate(mv, to, {
      duration: 1.8,
      ease: [0.22, 1, 0.36, 1],
      onUpdate: (v) =>
        setDisplay(
          v.toLocaleString("en-US", {
            minimumFractionDigits: decimals,
            maximumFractionDigits: decimals,
          })
        ),
    });
    return () => controls.stop();
  }, [inView, to, decimals, mv]);

  return (
    <span ref={ref}>
      {prefix}
      {display}
      {suffix}
    </span>
  );
}

const KPIS = [
  { value: <CountUp to={10000} suffix="+" />, labelKey: "stats.jobsCreated", sub: "By end of 2027" },
  { value: <CountUp to={0.1} suffix="%" decimals={1} />, labelKey: "stats.gdpShare", sub: "Real-economy share" },
  { value: <CountUp to={1000} suffix="" />, label: "Companies formalised", sub: "Under constitutional law" },
  { value: <CountUp to={100} prefix="" suffix="M EGP" />, label: "Annual tax revenue", sub: "Contributed to the state" },
  { value: <CountUp to={500} suffix="M EGP" />, label: "Annual exports", sub: "Generated by partners" },
  { value: <CountUp to={50000} suffix="+" />, label: "Workers insured", sub: "Newly NOSI-registered" },
];

const PERF = [
  { value: "99.95%", label: "Platform uptime" },
  { value: "< 50ms", label: "CRE validation p95" },
  { value: "850 r/s", label: "CRE throughput" },
  { value: "< 5 min", label: "KYC registration" },
];

export function Stats() {
  const { t } = useLanguage();
  return (
    <section className="relative overflow-hidden py-28 sm:py-36">
      <div className="absolute inset-0 -z-10 aurienta-grid opacity-25 [mask-image:radial-gradient(ellipse_at_center,black,transparent_75%)]" />
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <div className="flex flex-col items-center text-center">
          <div className="flex items-center gap-3">
            <span className="h-px w-10 bg-gradient-to-r from-transparent to-gold/50" />
            <GoldStar className="h-4 w-4" />
            <span className="font-sans text-[11px] font-medium uppercase tracking-[0.26em] text-gold-light/80">
              2027 Vision — Projected Outcomes
            </span>
            <GoldStar className="h-4 w-4" />
            <span className="h-px w-10 bg-gradient-to-l from-transparent to-gold/50" />
          </div>
          <h2 className="mt-6 max-w-3xl font-serif text-3xl font-semibold leading-[1.15] sm:text-4xl md:text-5xl">
            Structural trust, measured in
            <span className="text-gold-gradient"> real-economy outcomes.</span>
          </h2>
          <p className="mt-5 max-w-2xl font-sans text-base text-muted-foreground sm:text-lg">
            The figures below are <strong className="text-gold-light">2027 projections</strong> — the constitutional targets the platform is built to reach.
            For current live numbers, see the <a href="/trust" className="text-gold underline decoration-gold/40 underline-offset-4 hover:decoration-gold">live Trust Dashboard</a>.
          </p>
        </div>

        <div className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-gold/12 bg-gold/10 sm:grid-cols-2 lg:grid-cols-3">
          {KPIS.map((k, i) => (
            <motion.div
              key={k.label}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-40px" }}
              transition={{ delay: (i % 3) * 0.08, duration: 0.6 }}
              className="bg-background p-8"
            >
              <div className="font-serif text-4xl font-semibold text-gold-gradient sm:text-5xl">
                {k.value}
              </div>
              <div className="mt-3 font-sans text-sm font-medium text-foreground">{"labelKey" in k ? t(k.labelKey as string) : k.label}</div>
              <div className="font-sans text-xs text-muted-foreground">{k.sub}</div>
            </motion.div>
          ))}
        </div>

        <div className="mt-6 grid gap-4 rounded-2xl border border-gold/10 bg-background/40 p-6 sm:grid-cols-4 sm:p-8">
          {PERF.map((p) => (
            <div key={p.label} className="text-center">
              <div className="font-mono text-2xl font-semibold text-gold-light">{p.value}</div>
              <div className="mt-1 font-sans text-xs text-muted-foreground">{p.label}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
