// AURIENTA Institutional Architecture — Canonical Corporate Structure
// ═══════════════════════════════════════════════════════════════
// This file is the single source of truth for the AURIENTA
// institutional architecture. Every document, AI prompt, UI label,
// legal agreement, and developer reference must align with this file.
//
// DO NOT modify without Founder & Sole Owner approval.
// ═══════════════════════════════════════════════════════════════

export const INSTITUTIONAL_ARCHITECTURE = {
  group: "AURIENTA Holding Group",
  founder: "Mohamed Eltonsy",
  founderTitle: "Founder & Sole Owner",
  ownership: "100% — no co-founders, no shareholders, no investors, no equity dilution",

  entities: {
    holding: {
      name: "AURIENTA Holding Group",
      type: "Holding Company (non-operating)",
      responsibilities: [
        "Group Strategy",
        "Corporate Governance",
        "Constitutional Oversight",
        "Intellectual Property Ownership",
        "Trademarks",
        "Patents",
        "Licensing",
        "Investments",
        "Capital Allocation",
        "Corporate Finance",
        "Group Legal",
        "Enterprise Risk",
        "Internal Audit",
        "Long-Term Institutional Direction",
      ],
      owns: [
        "AURIENTA Operations (100%)",
        "AURIENTA Advisory (100%)",
        "All intellectual property (CRE, Brain AI, source code, trademarks, patents)",
        "All investments and licenses",
        "Future acquisitions",
        "Constitutional assets",
      ],
      doesNotDo: "Day-to-day operations",
    },

    operations: {
      name: "AURIENTA Operations",
      type: "Operating Company (technology + operations combined)",
      responsibilities: {
        technology: [
          "Constitutional Runtime Engine (CRE)",
          "Brain AI",
          "Engineering",
          "Product",
          "Enterprise Architecture",
          "Infrastructure",
          "Cloud",
          "DevOps",
          "Cybersecurity",
          "Artificial Intelligence",
          "Data",
          "APIs",
          "Internal Technology",
          "Developer Platform",
        ],
        operations: [
          "Enterprise Operations",
          "Platform Operations",
          "Customer Success",
          "Enterprise Success",
          "Compliance Operations",
          "Finance Operations",
          "Human Resources",
          "Administration",
          "Quality Assurance",
          "Marketing",
          "Communications",
          "Sales",
          "Business Operations",
          "Deployment",
          "Release Management",
          "Regional Expansion",
        ],
        regionalOperatingCompanies: [
          "AURIENTA Egypt",
          "AURIENTA GCC",
          "AURIENTA Africa",
          "AURIENTA Europe",
          "AURIENTA Asia",
          "AURIENTA Americas",
        ],
      },
      owns: "Nothing (Holding Group owns all IP)",
      manages: "All technology and operations for the Group",
    },

    advisory: {
      name: "AURIENTA Advisory",
      type: "Advisory Company (institutional ecosystem, non-software)",
      responsibilities: [
        "Strategic Partnerships",
        "Government Relations",
        "Regulatory Relations",
        "Professional Law Firm Network",
        "Accounting Firm Network",
        "Banking Partner Network",
        "University Network",
        "ERP Ecosystem",
        "Technology Alliances",
        "Cloud Provider Relationships",
        "Big Four Relationships",
        "Standards Organizations",
        "International Organizations",
        "Research Institutions",
        "Constitutional Consulting",
        "Constitutional Certification",
        "Training Programs",
        "Institutional Alliances",
        "Partner Accreditation",
        "Partner Success",
        "Professional Partner Network",
        "Institutional Business Development",
        "Cross-border Expansion Support",
      ],
      doesNotDo: "Software development (Advisory NEVER develops software)",
    },
  },

  scalabilityPrinciple: {
    title: "Constitutional Scalability Principle",
    text: "During the founder-led growth stage, Technology and Operations are intentionally combined into AURIENTA Operations. As the Group matures, AURIENTA Holding Group may establish an independent AURIENTA Technologies subsidiary without changing constitutional governance, enterprise architecture, institutional responsibilities, operating philosophy, blueprint, or constitutional model. The organizational evolution must not require redesign of the constitutional infrastructure — only legal restructuring.",
  },

  governanceModel: {
    holdingGroup: "Strategic ownership, corporate governance, capital allocation, group oversight",
    operations: "Execution, technology, operations, platform, product, regional businesses",
    advisory: "Institutional ecosystem, partnerships, certification, professional network, external relations",
    principle: "No responsibility overlap between entities",
  },
} as const;

// RACI Responsibility Matrix
// R = Responsible, A = Accountable, C = Consulted, I = Informed
export const RACI_MATRIX: Record<string, { holding: string; operations: string; advisory: string }> = {
  "Group Strategy": { holding: "A/R", operations: "C", advisory: "C" },
  "Corporate Governance": { holding: "A/R", operations: "I", advisory: "I" },
  "Constitutional Governance": { holding: "A", operations: "R", advisory: "C" },
  "Engineering": { holding: "I", operations: "A/R", advisory: "I" },
  "Product": { holding: "I", operations: "A/R", advisory: "C" },
  "Brain AI": { holding: "I", operations: "A/R", advisory: "I" },
  "CRE": { holding: "I", operations: "A/R", advisory: "I" },
  "Security": { holding: "A", operations: "R", advisory: "I" },
  "DevOps": { holding: "I", operations: "A/R", advisory: "I" },
  "Cloud": { holding: "I", operations: "A/R", advisory: "I" },
  "Infrastructure": { holding: "I", operations: "A/R", advisory: "I" },
  "Platform Operations": { holding: "I", operations: "A/R", advisory: "I" },
  "Enterprise Operations": { holding: "I", operations: "A/R", advisory: "I" },
  "Customer Success": { holding: "I", operations: "A/R", advisory: "C" },
  "Compliance Operations": { holding: "A", operations: "R", advisory: "C" },
  "Finance Operations": { holding: "A", operations: "R", advisory: "I" },
  "Human Resources": { holding: "A", operations: "R", advisory: "I" },
  "Marketing": { holding: "I", operations: "A/R", advisory: "C" },
  "Sales": { holding: "I", operations: "A/R", advisory: "C" },
  "Government Relations": { holding: "A", operations: "I", advisory: "R" },
  "Law Firm Network": { holding: "I", operations: "C", advisory: "A/R" },
  "Accounting Firm Network": { holding: "I", operations: "C", advisory: "A/R" },
  "Banking Partners": { holding: "I", operations: "C", advisory: "A/R" },
  "Universities": { holding: "I", operations: "C", advisory: "A/R" },
  "ERP Partners": { holding: "I", operations: "C", advisory: "A/R" },
  "Big Four Relationships": { holding: "I", operations: "C", advisory: "A/R" },
  "Certification": { holding: "A", operations: "I", advisory: "R" },
  "Standards Bodies": { holding: "I", operations: "I", advisory: "A/R" },
  "Licensing": { holding: "A/R", operations: "I", advisory: "C" },
  "Intellectual Property": { holding: "A/R", operations: "C", advisory: "I" },
  "Regional Expansion": { holding: "A", operations: "R", advisory: "C" },
  "Training Programs": { holding: "I", operations: "C", advisory: "A/R" },
  "Partner Accreditation": { holding: "I", operations: "I", advisory: "A/R" },
  "Internal Audit": { holding: "A/R", operations: "C", advisory: "I" },
  "Enterprise Risk": { holding: "A/R", operations: "C", advisory: "C" },
};
