// AURIENTA Legal Clauses — Egypt-Fortress Production v2.0
// ═══════════════════════════════════════════════════════════════
// Canonical legal clause text embedded in Master Service Agreements,
// Law Firm Partnership Agreements, and Bank Tripartite Agreements.
//
// These clauses are the contractual shield that operationalizes the
// zero-custody doctrine and the Hash-Only settlement architecture.
//
// DO NOT modify without Founder + Legal Counsel approval.
// Each clause has a stable CLAUSE_ID for audit-trail referencing.
// ═══════════════════════════════════════════════════════════════

export interface LegalClause {
  clauseId: string;
  title: string;
  agreementType: "MSA" | "LawFirmPartnership" | "BankTripartite" | "IntercompanySLA";
  parties: string[];
  text: string;
  purpose: string;
  legalBasis?: string;
}

// ═══════════════════════════════════════════════════════════════
// CLAUSE A — Binding Record (the core zero-custody shield)
// Embedded in EVERY MSA between AURIENTA OpCo/Tech and the Law Firm.
// ═══════════════════════════════════════════════════════════════
export const BINDING_RECORD_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-A-V1",
  title: "Binding Record Clause",
  agreementType: "MSA",
  parties: ["AURIENTA OpCo LLC", "AURIENTA Tech LLC", "Law Firm (Fiduciary)"],
  purpose:
    "Protects AURIENTA Middleware LLC from settlement disputes by establishing the CRE hash as the sole binding record of the settlement instruction.",
  text: `The Cryptographic Hash (SHA3-256) generated by the Constitutional Runtime Engine (CRE) at the instant of instruction finalization shall constitute the sole, binding, and conclusive record of the settlement instruction payload. AURIENTA Middleware LLC acts solely as a stateless, best-effort relay. Upon successful transmission of the signed payload to the receiving licensed party's API endpoint, AURIENTA Middleware LLC's obligation is fully discharged. It bears no liability for subsequent bank or law-firm execution latency, rejection, processing delays, or force majeure.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE B — Law Firm Fiduciary Mandate (Law Firm = Principal)
// Embedded in the Law Firm Partnership Agreement.
// ═══════════════════════════════════════════════════════════════
export const FIDUCIARY_MANDATE_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-B-V1",
  title: "Law Firm Fiduciary Mandate Clause",
  agreementType: "LawFirmPartnership",
  parties: ["Law Firm (Fiduciary)", "AURIENTA Middleware LLC", "AURIENTA OpCo LLC"],
  purpose:
    "Establishes the Law Firm as the legal Principal initiating payments, with AURIENTA Middleware acting only as its technical agent for hash generation and routing. This is what keeps AURIENTA outside the CBE PSP definition.",
  text: `The Law Firm hereby appoints AURIENTA Middleware LLC as its exclusive technical agent for the generation, cryptographic hashing, and routing of payment initiation instructions. The Law Firm confirms that any instruction signed by both the CRE System Private Key and the Law Firm's automated HSM key shall be deemed a direct, lawful order of the Law Firm as fiduciary custodian of the Escrow Account. The Law Firm retains sole legal authority over account activation, revocation, and override.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE C — Bank Regulatory Exemption
// Embedded in the Bank Tripartite Agreement.
// ═══════════════════════════════════════════════════════════════
export const BANK_EXEMPTION_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-C-V1",
  title: "Bank Regulatory Exemption Clause",
  agreementType: "BankTripartite",
  parties: ["CBE-Regulated Partner Bank", "AURIENTA OpCo LLC", "Law Firm (Fiduciary)"],
  purpose:
    "Binds the Bank to acknowledge AURIENTA's software-vendor status under Law 194/2020 and Law 5/2022, ensuring dual-signed instructions are executed without reclassifying AURIENTA as a PSP.",
  legalBasis: "Law 194/2020 (Banking) + Law 5/2022 (FinTech)",
  text: `The Bank acknowledges that AURIENTA OpCo LLC operates solely as an outsourced software provider under Law 194/2020 and Law 5/2022, and does not hold, clear, or settle funds. The Bank agrees to execute API settlement instructions exclusively from the designated Fiduciary Escrow Account upon cryptographic verification of dual-authorization (CRE Key 1 + Law Firm HSM Key 2). The Bank shall not classify AURIENTA as a Payment Initiation Service Provider (PISP) under any circumstances, provided the dual-signature requirement is maintained.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE D — Fiduciary Kill-Switch
// The Law Firm's unilateral right to revoke without breach liability.
// ═══════════════════════════════════════════════════════════════
export const KILL_SWITCH_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-D-V1",
  title: "Fiduciary Kill-Switch Clause",
  agreementType: "BankTripartite",
  parties: ["Law Firm (Fiduciary)", "AURIENTA OpCo LLC", "CBE-Regulated Partner Bank"],
  purpose:
    "The Law Firm's unilateral right to revoke its HSM Key or trigger a Fiduciary Pause without incurring breach-of-contract liability. This is the legal mechanism that makes the dual-key model meaningful.",
  text: `The Law Firm reserves the absolute right to unilaterally revoke its API HSM Key or trigger a 'Fiduciary Pause' on the Escrow Account via bank portal or API command at any time upon detecting fraud, insolvency, or court order, without incurring breach-of-contract liability to AURIENTA. The Law Firm shall provide written notice to AURIENTA OpCo LLC and the Bank within 24 hours of any such revocation, specifying the cause and expected duration. The Law Firm's HSM Key revocation automatically suspends all dual-signed settlement instructions until the Key is reinstated or replaced.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE E — CRE Hash as Sole Binding Record (extended)
// Locks the hash as the conclusive record + 72-hour key-compromise window.
// ═══════════════════════════════════════════════════════════════
export const CRE_HASH_BINDING_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-E-V1",
  title: "CRE Hash as Binding Record Clause",
  agreementType: "BankTripartite",
  parties: ["Law Firm (Fiduciary)", "AURIENTA OpCo LLC", "CBE-Regulated Partner Bank"],
  purpose:
    "Locks in the hash as the conclusive record of the transaction instruction and closes the 'I didn't authorize this' defense loophole. Creates a 72-hour window for key compromise reporting — a standard security-incident clause.",
  text: `The Parties agree that the SHA3-256 hash of the dual-signed CRE instruction payload, once persisted to the immutable ledger, shall constitute the sole and binding record of the transaction instruction. No party may dispute the validity of a transaction for which a valid dual-signed hash exists on the ledger, except in cases of proven cryptographic key compromise documented within 72 hours of detection. Key compromise must be reported simultaneously to all three Parties (Law Firm, AURIENTA OpCo, Bank) and triggers immediate suspension of the affected HSM Key pending forensic review.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE F — Antifragility Vault Segregation
// Ensures AURIENTA has zero legal claim on the 0.5% Reserve.
// ═══════════════════════════════════════════════════════════════
export const ANTIFRAGILITY_VAULT_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-F-V1",
  title: "Antifragility Vault Segregation Clause",
  agreementType: "BankTripartite",
  parties: ["Law Firm (Fiduciary)", "Enterprise SPVs (Beneficiaries)", "AURIENTA OpCo LLC"],
  purpose:
    "Establishes the Antifragility Vault as a segregated fiduciary account at the CBE Partner Bank, owned by the Law Firm on behalf of Enterprise SPVs as beneficiaries. AURIENTA has zero legal claim on it.",
  text: `The Antifragility Vault, funded by the 0.5% reserve deduction from each milestone release, shall be maintained as a segregated fiduciary account at the CBE-Regulated Partner Bank, legally owned by the Law Firm on behalf of the Enterprise SPVs as beneficiaries. AURIENTA Holding S.A.E., AURIENTA OpCo LLC, AURIENTA Tech LLC, AURIENTA Advisory LLC, and AURIENTA Middleware LLC shall have zero legal claim, lien, or security interest over the Antifragility Vault. Disbursement from the Vault requires dual-signed instruction (Law Firm HSM + CRE) consistent with the Atomic Split-Settlement flow, or a court order.`,
};

// ═══════════════════════════════════════════════════════════════
// CLAUSE G — Intercompany IP License (Tech → OpCo)
// Arm's-length royalty under Law 91/2005.
// ═══════════════════════════════════════════════════════════════
export const INTERCOMPANY_IP_LICENSE_CLAUSE: LegalClause = {
  clauseId: "AUR-CLAUSE-G-V1",
  title: "Intercompany IP License Clause",
  agreementType: "IntercompanySLA",
  parties: ["AURIENTA Tech LLC (Licensor)", "AURIENTA OpCo LLC (Licensee)"],
  purpose:
    "Arm's-length royalty agreement between Tech LLC (IP owner) and OpCo LLC (operator). Transfer-priced per Law 91/2005. Ensures IP is ring-fenced from OpCo's operating liability.",
  legalBasis: "Law 91/2005 (Egyptian Transfer Pricing)",
  text: `AURIENTA Tech LLC, as sole legal owner of all AURIENTA intellectual property (CRE source code, Rego policies, JOZOUR v3, EVE, graph models, Constitutional Blueprint, trademarks, and AI routing logic), hereby grants AURIENTA OpCo LLC a non-exclusive, non-transferable, revocable license to operate the IP for client-facing platform purposes. OpCo shall pay Tech LLC a royalty calculated on an arm's-length basis consistent with Law 91/2005 and documented in an annual Transfer Pricing Study. Upon termination or insolvency of OpCo, the license automatically reverts to Tech LLC, and OpCo shall cease all use of the IP within 30 days.`,
};

// ═══════════════════════════════════════════════════════════════
// ALL CLAUSES — exported as a registry for the audit trail
// ═══════════════════════════════════════════════════════════════
export const ALL_LEGAL_CLAUSES: LegalClause[] = [
  BINDING_RECORD_CLAUSE,
  FIDUCIARY_MANDATE_CLAUSE,
  BANK_EXEMPTION_CLAUSE,
  KILL_SWITCH_CLAUSE,
  CRE_HASH_BINDING_CLAUSE,
  ANTIFRAGILITY_VAULT_CLAUSE,
  INTERCOMPANY_IP_LICENSE_CLAUSE,
];

export const LEGAL_CLAUSES_REGISTRY = {
  version: "2.0-egypt-fortress",
  adopted: "2026-09-02",
  totalClauses: ALL_LEGAL_CLAUSES.length,
  byAgreementType: {
    MSA: ALL_LEGAL_CLAUSES.filter((c) => c.agreementType === "MSA").map((c) => c.clauseId),
    LawFirmPartnership: ALL_LEGAL_CLAUSES.filter((c) => c.agreementType === "LawFirmPartnership").map((c) => c.clauseId),
    BankTripartite: ALL_LEGAL_CLAUSES.filter((c) => c.agreementType === "BankTripartite").map((c) => c.clauseId),
    IntercompanySLA: ALL_LEGAL_CLAUSES.filter((c) => c.agreementType === "IntercompanySLA").map((c) => c.clauseId),
  },
} as const;
